# Generated by Django 2.1.4 on 2019-01-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='interested',
        ),
    ]
